version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mozara-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mozara
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./springboot/db/mozara.sql:/docker-entrypoint-initdb.d/mozara.sql:ro
      - ./springboot/db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - mozara-network

  spring-backend:
    build: ./springboot
    container_name: mozara-spring
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mozara?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - mozara-network

  python-backend:
    build: ./python
    container_name: mozara-python
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_INDEX_HOST: ${PINECONE_INDEX_HOST}
    networks:
      - mozara-network
    volumes:
      - ./hair_damage:/app/hair_damage
    mem_limit: 8g

  frontend:
    build: ../frontend
    container_name: mozara-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - spring-backend
      - python-backend
    networks:
      - mozara-network


volumes:
  mysql_data:
    driver: local

networks:
  mozara-network:
    driver: bridge
    name: mozara-network