from typing import Dict, List, Any

# 탈모 단계별 제품 데이터 구조 (app.py에서 분리)
HAIR_LOSS_STAGE_PRODUCTS: Dict[int, List[dict]] = {
    1: [
        {
            "productId": "stage1-1",
            "productName": "두피 건강 샴푸",
            "productPrice": 18000,
            "productRating": 4.5,
            "productReviewCount": 234,
            "productImage": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage1-1",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "두피케어",
            "category1": "헤어케어",
            "category2": "탈모샴푸",
            "category3": "예방용",
            "category4": "1단계",
            "description": "두피 건강을 위한 예방 중심 샴푸",
            "ingredients": ["케라틴", "비오틴", "판테놀"],
            "suitableStages": [1, 2],
        },
        {
            "productId": "stage1-2",
            "productName": "두피 토닉",
            "productPrice": 22000,
            "productRating": 4.3,
            "productReviewCount": 189,
            "productImage": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage1-2",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "두피케어",
            "category1": "헤어케어",
            "category2": "헤어토닉",
            "category3": "예방용",
            "category4": "1단계",
            "description": "두피 순환을 개선하는 토닉",
            "ingredients": ["민들레 추출물", "로즈마리", "멘톨"],
            "suitableStages": [1, 2],
        },
        {
            "productId": "stage1-3",
            "productName": "비오틴 영양제",
            "productPrice": 35000,
            "productRating": 4.7,
            "productReviewCount": 156,
            "productImage": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage1-3",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "두피케어",
            "category1": "헤어케어",
            "category2": "영양제",
            "category3": "비오틴",
            "category4": "1단계",
            "description": "모발 건강을 위한 비오틴 영양제",
            "ingredients": ["비오틴", "아연", "셀레늄"],
            "suitableStages": [1, 2, 3],
        },
    ],
    2: [
        {
            "productId": "stage2-1",
            "productName": "탈모 방지 샴푸",
            "productPrice": 25000,
            "productRating": 4.6,
            "productReviewCount": 267,
            "productImage": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage2-1",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "탈모케어",
            "category1": "헤어케어",
            "category2": "탈모샴푸",
            "category3": "방지용",
            "category4": "2단계",
            "description": "경미한 탈모를 방지하는 샴푸",
            "ingredients": ["케라틴", "비오틴", "판테놀", "아르간 오일"],
            "suitableStages": [2, 3],
        },
        {
            "productId": "stage2-2",
            "productName": "모발 강화 세럼",
            "productPrice": 38000,
            "productRating": 4.4,
            "productReviewCount": 198,
            "productImage": "https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage2-2",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "탈모케어",
            "category1": "헤어케어",
            "category2": "헤어세럼",
            "category3": "강화용",
            "category4": "2단계",
            "description": "모발 성장을 촉진하는 세럼",
            "ingredients": ["펩타이드", "케라틴", "비타민 E"],
            "suitableStages": [2, 3, 4],
        },
    ],
    3: [
        {
            "productId": "stage3-1",
            "productName": "탈모 치료 샴푸",
            "productPrice": 35000,
            "productRating": 4.8,
            "productReviewCount": 312,
            "productImage": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage3-1",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "탈모치료",
            "category1": "헤어케어",
            "category2": "탈모샴푸",
            "category3": "치료용",
            "category4": "3단계",
            "description": "탈모 진행을 억제하는 치료 샴푸",
            "ingredients": ["케토코나졸", "케라틴", "아르간 오일"],
            "suitableStages": [3, 4],
        },
        {
            "productId": "stage3-2",
            "productName": "미녹시딜 토닉",
            "productPrice": 45000,
            "productRating": 4.9,
            "productReviewCount": 278,
            "productImage": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage3-2",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "탈모치료",
            "category1": "헤어케어",
            "category2": "헤어토닉",
            "category3": "치료용",
            "category4": "3단계",
            "description": "모발 성장을 촉진하는 미녹시딜 토닉",
            "ingredients": ["미녹시딜 5%", "케라틴", "아미노산"],
            "suitableStages": [3, 4, 5],
        },
    ],
    4: [
        {
            "productId": "stage4-1",
            "productName": "강력 탈모 치료 샴푸",
            "productPrice": 45000,
            "productRating": 4.9,
            "productReviewCount": 345,
            "productImage": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage4-1",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "강력탈모치료",
            "category1": "헤어케어",
            "category2": "탈모샴푸",
            "category3": "강력치료용",
            "category4": "4단계",
            "description": "심한 탈모를 위한 강력 치료 샴푸",
            "ingredients": ["케토코나졸 2%", "케라틴", "아르간 오일", "프로바이오틱스"],
            "suitableStages": [4, 5],
        },
        {
            "productId": "stage4-2",
            "productName": "고농도 미녹시딜 토닉",
            "productPrice": 65000,
            "productRating": 4.9,
            "productReviewCount": 298,
            "productImage": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage4-2",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "강력탈모치료",
            "category1": "헤어케어",
            "category2": "헤어토닉",
            "category3": "강력치료용",
            "category4": "4단계",
            "description": "고농도 미녹시딜로 모발 성장 촉진",
            "ingredients": ["미녹시딜 10%", "케라틴", "아미노산", "펩타이드"],
            "suitableStages": [4, 5, 6],
        },
    ],
    5: [
        {
            "productId": "stage5-1",
            "productName": "프리미엄 탈모 치료 샴푸",
            "productPrice": 65000,
            "productRating": 4.9,
            "productReviewCount": 423,
            "productImage": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage5-1",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "프리미엄탈모치료",
            "category1": "헤어케어",
            "category2": "탈모샴푸",
            "category3": "프리미엄치료용",
            "category4": "5단계",
            "description": "매우 심한 탈모를 위한 프리미엄 치료 샴푸",
            "ingredients": ["케토코나졸 2%", "케라틴", "아르간 오일", "프로바이오틱스", "펩타이드"],
            "suitableStages": [5, 6],
        },
        {
            "productId": "stage5-2",
            "productName": "최고농도 미녹시딜 토닉",
            "productPrice": 85000,
            "productRating": 4.9,
            "productReviewCount": 356,
            "productImage": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage5-2",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "프리미엄탈모치료",
            "category1": "헤어케어",
            "category2": "헤어토닉",
            "category3": "프리미엄치료용",
            "category4": "5단계",
            "description": "최고농도 미녹시딜로 모발 성장 촉진",
            "ingredients": ["미녹시딜 15%", "케라틴", "아미노산", "펩타이드", "비타민 E"],
            "suitableStages": [5, 6],
        },
    ],
    6: [
        {
            "productId": "stage6-1",
            "productName": "의료진 상담 필수 샴푸",
            "productPrice": 75000,
            "productRating": 4.8,
            "productReviewCount": 234,
            "productImage": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage6-1",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "의료진상담필수",
            "category1": "헤어케어",
            "category2": "탈모샴푸",
            "category3": "의료진상담용",
            "category4": "6단계",
            "description": "극심한 탈모를 위한 의료진 상담 필수 샴푸",
            "ingredients": ["케토코나졸 2%", "케라틴", "아르간 오일", "프로바이오틱스", "펩타이드", "의료용 성분"],
            "suitableStages": [6],
        },
        {
            "productId": "stage6-2",
            "productName": "의료진 처방 토닉",
            "productPrice": 95000,
            "productRating": 4.9,
            "productReviewCount": 189,
            "productImage": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage6-2",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "의료진상담필수",
            "category1": "헤어케어",
            "category2": "헤어토닉",
            "category3": "의료진처방용",
            "category4": "6단계",
            "description": "극심한 탈모를 위한 의료진 처방 토닉",
            "ingredients": ["미녹시딜 20%", "케라틴", "아미노산", "펩타이드", "비타민 E", "의료용 성분"],
            "suitableStages": [6],
        },
    ],
}

STAGE_DESCRIPTIONS = {
    1: "초기 탈모 (예방 중심)",
    2: "경미한 탈모 (강화 중심)",
    3: "중등도 탈모 (치료 중심)",
    4: "심한 탈모 (집중 치료)",
    5: "매우 심한 탈모 (전문 치료)",
    6: "극심한 탈모 (의료진 상담 필수)",
}


